services:
    pitech_mailer.logger:
        class: Pitech\MailerBundle\Logger\MailerLogger
        arguments:
            - pitech_mailer
            - [@pitech_mailer.logger.handler]

    pitech_mailer.logger.handler:
        class: Monolog\Handler\StreamHandler
        arguments: [%kernel.logs_dir%/pitech_mailer.log]
